apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
      - name: mlops-api
        image: akshaysutar10/mlops-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000